# Generated by Django 6.0.4 on 2026-04-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
