# Generated by Django 4.2.4 on 2023-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.TextField()),
                ('details', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
    ]
