# Generated by Django 4.2.16 on 2026-04-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_unify_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
    ]
